### ISSUE TITLE
Fix hanging tests

### ISSUE THREAD

**Issue by glebec** [World-of-Code/code-mode#51]
`npm test` hangs indefinitely after test results. Something in the process is presenting normal exit.

Bad commits:

* 701235c

Good commits:

* dd05fc3
* b9ecc85
* 2be4221
* 69491cc

All of the above were tested by `rm -rf node_modules && yarn && yarn test`. Currently bisecting, will report back.

---

### Bisection

Nuking node_modules each time, re-installing, testing, and fixing broken tests, I ran the following bisection:

```
git bisect start
# bad: [701235c0276b29ad6fcc1f79765a8a9a355831d0] feat: rename jsx components
git bisect bad 701235c0276b29ad6fcc1f79765a8a9a355831d0
# good: [dd05fc31699ad9b354f0e95af8493dc49692510e] Merge pull request #6 from TheUniverseofCoding/f/boilermaker-integration
git bisect good dd05fc31699ad9b354f0e95af8493dc49692510e
# bad: [88510b38fdea033a695e6990e5da46872a9968b6] Merge branch 'master' of https://github.com/TheUniverseofCoding/world-of-code
git bisect bad 88510b38fdea033a695e6990e5da46872a9968b6
# bad: [88510b38fdea033a695e6990e5da46872a9968b6] Merge branch 'master' of https://github.com/TheUniverseofCoding/world-of-code
git bisect bad 88510b38fdea033a695e6990e5da46872a9968b6
# bad: [2486c464113400546a0028a341ec7324939de99f] Merge pull request #7 from TheUniverseofCoding/f/prepare-repl-integration
git bisect bad 2486c464113400546a0028a341ec7324939de99f
# bad: [6bcce75de908305a81f9a96f0f5ed02f22ba83bf] feat: add mocha
git bisect bad 6bcce75de908305a81f9a96f0f5ed02f22ba83bf
# good: [51d800fb4c9b0373b130280f346c8cfd770ae8e0] feat: make ready for repl integration
git bisect good 51d800fb4c9b0373b130280f346c8cfd770ae8e0
# first bad commit: [6bcce75de908305a81f9a96f0f5ed02f22ba83bf] feat: add mocha
```

**Comment by glebec** [comment]
Problem ID'd. It was introduced [here](https://github.com/TheUniverseofCoding/world-of-code/commit/6bcce75de908305a81f9a96f0f5ed02f22ba83bf#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R79) when upgrading Mocha from v3 to v4.

As the [v4 release notes](https://github.com/mochajs/mocha/releases/tag/v4.0.0) indicate:

> By default, Mocha will no longer force the process to exit once all tests complete. This means any test code (or code under test) which would normally prevent node from exiting will do so when run in Mocha. Supply the `--exit` flag to revert to pre-v4.0.0 behavior.

Possible solutions:

- **supply `--exit` (easiest, masks true problem)** <--- recommend
- downgrade to mocha v3 (easy, masks true problem, regressive)
- use global `after` to cleanup whatever is hanging (best but hardest, see below)

**Comment by glebec** [comment]
Following advice from [this Mocha issue](https://github.com/mochajs/mocha/issues/3044) and using a debugging trick from [this gist](https://gist.github.com/boneskull/7fe75b63d613fa940db7ec990a5f5843), I discovered that an undocumented interval was being created by [this line of `connect-session-sequelize`](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L152). Thankfully, an undocumented method at [this line](https://github.com/mweibel/connect-session-sequelize/blob/ab3a3e2c73721a345101a398af2e2073817c9b6f/lib/connect-session-sequelize.js#L158) meant that the following cleanup hook works:

```js
// in app module

app.set('sessionStore', sessionStore)
```

```js
// in spec

after('clean up db cnxn', () => {
  console.log('closing db')
  db.close()
})

after('clean up resources', () => {
  console.log('stopping session store expiration interval')
  app.get('sessionStore').stopExpiringSessions()
})
```

This is probably more trouble than it is worth for a demo project.

**Comment by veekas** [comment]
Wow, thanks for all your work, @glebec. This is fascinating. We'll implement the first method, as you suggest.
